/**
 * Build-time script: copies the overlay binary into the CLI package and
 * generates a TypeScript shim that uses Bun's file embedding.
 *
 * This avoids base64 encoding — the binary is embedded as raw bytes
 * in the compiled executable, eliminating ~33% size overhead.
 *
 * Run: bun run packages/cli/src/embedOverlay.ts
 */

import { existsSync, copyFileSync, statSync, writeFileSync } from "fs";
import { resolve } from "path";

const OVERLAY_BIN = resolve(import.meta.dirname, "../../overlay/target/release/golem-overlay");
const COPY_DEST = resolve(import.meta.dirname, "../golem-overlay.bin");
const SHIM_FILE = resolve(import.meta.dirname, "embeddedOverlay.generated.ts");

if (!existsSync(OVERLAY_BIN)) {
  console.error(`[embed-overlay] Overlay binary not found at ${OVERLAY_BIN}`);
  console.error("[embed-overlay] Build it first: cd packages/overlay && cargo build --release");
  process.exit(1);
}

// Copy overlay binary to a location the bundler can find
copyFileSync(OVERLAY_BIN, COPY_DEST);

// Generate a shim that uses Bun's file embedding (raw bytes, no base64)
const shim = `// AUTO-GENERATED by embedOverlay.ts — do not edit
// @ts-ignore — only resolves in compiled binaries
import path from "../golem-overlay.bin" with { type: "file" };
export const EMBEDDED_OVERLAY_PATH: string = path;
`;

writeFileSync(SHIM_FILE, shim);

const size = statSync(OVERLAY_BIN).size;
console.log(`[embed-overlay] Prepared overlay binary (${(size / 1024 / 1024).toFixed(1)} MB) for embedding`);
