/**
 * Build-time script: reads packages/frontend/dist/ and generates
 * an embeddedAssets.ts module that inlines all files as base64.
 *
 * Run: bun run packages/cli/src/embedAssets.ts
 */

import { readdirSync, statSync, readFileSync, writeFileSync } from "fs";
import { join, relative, resolve } from "path";

const DIST_DIR = resolve(import.meta.dirname, "../../frontend/dist");
const OUT_FILE = resolve(import.meta.dirname, "embeddedAssets.generated.ts");

function walkDir(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...walkDir(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

const files = walkDir(DIST_DIR);
const entries: string[] = [];

for (const file of files) {
  const relPath = "/" + relative(DIST_DIR, file);
  const content = readFileSync(file);
  const b64 = content.toString("base64");
  entries.push(`  ${JSON.stringify(relPath)}: { data: Buffer.from(${JSON.stringify(b64)}, "base64"), size: ${content.length} }`);
}

const output = `// AUTO-GENERATED by embedAssets.ts — do not edit
export const EMBEDDED_ASSETS: Record<string, { data: Buffer; size: number }> = {
${entries.join(",\n")},
};
`;

writeFileSync(OUT_FILE, output);
console.log(`[embed] Wrote ${files.length} files to ${OUT_FILE}`);
