/**
 * Build-time script: reads the compiled overlay binary and generates
 * an embeddedOverlay.generated.ts module that inlines it as base64.
 *
 * Run: bun run packages/cli/src/embedOverlay.ts
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";

const OVERLAY_BIN = resolve(import.meta.dirname, "../../overlay/target/release/golem-overlay");
const OUT_FILE = resolve(import.meta.dirname, "embeddedOverlay.generated.ts");

if (!existsSync(OVERLAY_BIN)) {
  console.error(`[embed-overlay] Overlay binary not found at ${OVERLAY_BIN}`);
  console.error("[embed-overlay] Build it first: cd packages/overlay && cargo build --release");
  process.exit(1);
}

const content = readFileSync(OVERLAY_BIN);
const b64 = content.toString("base64");

const output = `// AUTO-GENERATED by embedOverlay.ts — do not edit
export const EMBEDDED_OVERLAY_BASE64 = ${JSON.stringify(b64)};
export const EMBEDDED_OVERLAY_SIZE = ${content.length};
`;

writeFileSync(OUT_FILE, output);
console.log(`[embed-overlay] Wrote overlay binary (${(content.length / 1024 / 1024).toFixed(1)} MB) to ${OUT_FILE}`);
